### ISSUE TITLE
Single IMEI no. returned for dual sim device(has two imei nos.)

### ISSUE THREAD

**Issue by thatsmekaustubh** [kapetan/cordova-plugin-android-imei#2]
I have been trying to implement this plugin for a project using online Ionic Creator tool (1.1 ver.) and it did return imei no. but,
my device is dual sim and has two IMEI nos. plugin only returned one; please help me understand if I am missing something or is it that it returns only single imei if so which one it is 1st, or 2nd
Device details : Redmi Note 5 / Android 7.1.2

**Comment by kapetan** [comment]
I really don't know. Hope you found your answer.
